pipeline {
    /*agent { docker { image 'node:6.3' } }*/
    agent any
    stages {
        stage('Testing Pipeline') {
            steps {
                sh 'echo "This is a demo step of pipeline"'
            }
        }
        stage('Pipeline Utility Tester') {
            steps {
                sh 'echo "Reading yaml data from config.yml file"'
                script{datas = readYaml (file: 'config.yml') }
                sh 'echo "Size of data is :"' 
                datas.size().toString()
                sh 'echo "Content in the data is :"' 
                datas.config.toString()
            }    
        }
    
    }
}
